# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

variables:
- group: secret
- name: imageName
  value: 'dmz_ai.go:latest'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DownloadSecureFile@1
      name: env
      displayName: 'Download .env File'
      inputs:
        secureFile: '.env'
    - script: |
        cp $(env.secureFilePath) ./.env
        docker-compose build
        docker login -u swsaturn -p $(DOCKER_HUB_PWD)
        docker-compose push
      displayName: 'docker-compose build and push'
