# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
- group: secret
- name: imageName
  value: 'dmz_ai.go:$(build.buildId)'

steps:
- task: DownloadSecureFile@1
  name: env
  displayName: 'Download .env File'
  inputs:
    secureFile: '.env'
- script: |
    docker build -f **/Dockerfile -t swsaturn/$(imageName) .
    docker login -u swsaturn -p $(DOCKER_HUB_PWD)
    docker push swsaturn/$(imageName)
  displayName: 'docker build and push'